language: shell

os: linux

dist: bionic

services:
  - docker

before_install:
  - cat .travis_dockerfile | docker build -t ao:travis -

script:
  - docker run -v $(pwd):/root ao:travis su -l -c "make all"

before_deploy:
  - docker run -v $(pwd):/root ao:travis su -l -c "make -s ALL"
  - make -C uSDCard all

deploy:
  provider: releases
  edge: true
  token:
    secure: $SECURE_TOKEN
  on:
    tags: true
  overwrite: true
  file_glob: true
  file: mpmd_marlin_1.1.x-*.{bin,otx,map,elf,zip}
  prerelease: true
  target_commitish: master
